include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SlipperyIndicator
SlipperyIndicator_FILES = Tweak.xm
SlipperyIndicator_CFLAGS = -fobjc-arc -Wno-arc-performSelector-leaks
SlipperyIndicator_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include $(THEOS_MAKE_PATH)/tweak.mk
